// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.4

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type MessageSystemHTTPServer interface {
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
}

func RegisterMessageSystemHTTPServer(s *http.Server, srv MessageSystemHTTPServer) {
	r := s.Route("/")
	r.POST("/raiden/v1/send_msg", _MessageSystem_SendMessage0_HTTP_Handler(srv))
}

func _MessageSystem_SendMessage0_HTTP_Handler(srv MessageSystemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/raiden.v1.MessageSystem/SendMessage")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*SendMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendMessageReply)
		return ctx.Result(200, reply)
	}
}

type MessageSystemHTTPClient interface {
	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...http.CallOption) (rsp *SendMessageReply, err error)
}

type MessageSystemHTTPClientImpl struct {
	cc *http.Client
}

func NewMessageSystemHTTPClient(client *http.Client) MessageSystemHTTPClient {
	return &MessageSystemHTTPClientImpl{client}
}

func (c *MessageSystemHTTPClientImpl) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...http.CallOption) (*SendMessageReply, error) {
	var out SendMessageReply
	pattern := "/raiden/v1/send_msg"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/raiden.v1.MessageSystem/SendMessage"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
