// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RdMessageColumns holds the columns for the "rd_message" table.
	RdMessageColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true},
		{Name: "sender_uid", Type: field.TypeInt32, Nullable: true},
		{Name: "recver_uid", Type: field.TypeInt32, Nullable: true},
		{Name: "content", Type: field.TypeJSON},
		{Name: "create_time", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// RdMessageTable holds the schema information for the "rd_message" table.
	RdMessageTable = &schema.Table{
		Name:       "rd_message",
		Columns:    RdMessageColumns,
		PrimaryKey: []*schema.Column{RdMessageColumns[0]},
	}
	// RdMomentColumns holds the columns for the "rd_moment" table.
	RdMomentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "type", Type: field.TypeInt32, Nullable: true, Default: 1},
		{Name: "by_uid", Type: field.TypeInt32, Nullable: true},
		{Name: "txt", Type: field.TypeString, Size: 2147483647},
		{Name: "imgs", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeInt32, Nullable: true},
		{Name: "publish_time", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// RdMomentTable holds the schema information for the "rd_moment" table.
	RdMomentTable = &schema.Table{
		Name:       "rd_moment",
		Columns:    RdMomentColumns,
		PrimaryKey: []*schema.Column{RdMomentColumns[0]},
	}
	// RdRMomentsFollowingColumns holds the columns for the "rd_r_moments_following" table.
	RdRMomentsFollowingColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "moment_id", Type: field.TypeInt64, Nullable: true, Default: 1},
		{Name: "moment_type", Type: field.TypeInt32, Nullable: true, Default: 1},
		{Name: "by_uid", Type: field.TypeInt32, Nullable: true},
		{Name: "for_uid", Type: field.TypeInt32, Nullable: true},
		{Name: "txt", Type: field.TypeString, Size: 2147483647},
		{Name: "imgs", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeInt32, Nullable: true},
		{Name: "publish_time", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// RdRMomentsFollowingTable holds the schema information for the "rd_r_moments_following" table.
	RdRMomentsFollowingTable = &schema.Table{
		Name:       "rd_r_moments_following",
		Columns:    RdRMomentsFollowingColumns,
		PrimaryKey: []*schema.Column{RdRMomentsFollowingColumns[0]},
	}
	// RdRUserFollowersColumns holds the columns for the "rd_r_user_followers" table.
	RdRUserFollowersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "uid", Type: field.TypeInt32, Nullable: true},
		{Name: "followers_uid", Type: field.TypeInt32, Nullable: true},
		{Name: "create_time", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// RdRUserFollowersTable holds the schema information for the "rd_r_user_followers" table.
	RdRUserFollowersTable = &schema.Table{
		Name:       "rd_r_user_followers",
		Columns:    RdRUserFollowersColumns,
		PrimaryKey: []*schema.Column{RdRUserFollowersColumns[0]},
	}
	// RdRUserFollowingColumns holds the columns for the "rd_r_user_following" table.
	RdRUserFollowingColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "uid", Type: field.TypeInt32, Nullable: true},
		{Name: "following_uid", Type: field.TypeInt32, Nullable: true},
		{Name: "create_time", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// RdRUserFollowingTable holds the schema information for the "rd_r_user_following" table.
	RdRUserFollowingTable = &schema.Table{
		Name:       "rd_r_user_following",
		Columns:    RdRUserFollowingColumns,
		PrimaryKey: []*schema.Column{RdRUserFollowingColumns[0]},
	}
	// RdUserColumns holds the columns for the "rd_user" table.
	RdUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true},
		{Name: "nick", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt32, Default: 1},
		{Name: "create_time", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// RdUserTable holds the schema information for the "rd_user" table.
	RdUserTable = &schema.Table{
		Name:       "rd_user",
		Columns:    RdUserColumns,
		PrimaryKey: []*schema.Column{RdUserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RdMessageTable,
		RdMomentTable,
		RdRMomentsFollowingTable,
		RdRUserFollowersTable,
		RdRUserFollowingTable,
		RdUserTable,
	}
)

func init() {
	RdMessageTable.Annotation = &entsql.Annotation{
		Table: "rd_message",
	}
	RdMomentTable.Annotation = &entsql.Annotation{
		Table: "rd_moment",
	}
	RdRMomentsFollowingTable.Annotation = &entsql.Annotation{
		Table: "rd_r_moments_following",
	}
	RdRUserFollowersTable.Annotation = &entsql.Annotation{
		Table: "rd_r_user_followers",
	}
	RdRUserFollowingTable.Annotation = &entsql.Annotation{
		Table: "rd_r_user_following",
	}
	RdUserTable.Annotation = &entsql.Annotation{
		Table: "rd_user",
	}
}
