// Code generated by ent, DO NOT EDIT.

package rdruserfollowing

import (
	"time"
)

const (
	// Label holds the string label denoting the rdruserfollowing type in the database.
	Label = "rd_ruser_following"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldFollowingUID holds the string denoting the following_uid field in the database.
	FieldFollowingUID = "following_uid"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// Table holds the table name of the rdruserfollowing in the database.
	Table = "rd_r_user_following"
)

// Columns holds all SQL columns for rdruserfollowing fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldFollowingUID,
	FieldCreateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
)
