// Code generated by ent, DO NOT EDIT.

package rdruserfollowers

import (
	"time"
)

const (
	// Label holds the string label denoting the rdruserfollowers type in the database.
	Label = "rd_ruser_followers"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldFollowersUID holds the string denoting the followers_uid field in the database.
	FieldFollowersUID = "followers_uid"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// Table holds the table name of the rdruserfollowers in the database.
	Table = "rd_r_user_followers"
)

// Columns holds all SQL columns for rdruserfollowers fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldFollowersUID,
	FieldCreateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
)
