// Code generated by ent, DO NOT EDIT.

package rdruserfollowers

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldLTE(FieldID, id))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldEQ(FieldUID, v))
}

// FollowersUID applies equality check predicate on the "followers_uid" field. It's identical to FollowersUIDEQ.
func FollowersUID(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldEQ(FieldFollowersUID, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldEQ(FieldCreateTime, v))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldLTE(FieldUID, v))
}

// UIDIsNil applies the IsNil predicate on the "uid" field.
func UIDIsNil() predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldIsNull(FieldUID))
}

// UIDNotNil applies the NotNil predicate on the "uid" field.
func UIDNotNil() predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldNotNull(FieldUID))
}

// FollowersUIDEQ applies the EQ predicate on the "followers_uid" field.
func FollowersUIDEQ(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldEQ(FieldFollowersUID, v))
}

// FollowersUIDNEQ applies the NEQ predicate on the "followers_uid" field.
func FollowersUIDNEQ(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldNEQ(FieldFollowersUID, v))
}

// FollowersUIDIn applies the In predicate on the "followers_uid" field.
func FollowersUIDIn(vs ...int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldIn(FieldFollowersUID, vs...))
}

// FollowersUIDNotIn applies the NotIn predicate on the "followers_uid" field.
func FollowersUIDNotIn(vs ...int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldNotIn(FieldFollowersUID, vs...))
}

// FollowersUIDGT applies the GT predicate on the "followers_uid" field.
func FollowersUIDGT(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldGT(FieldFollowersUID, v))
}

// FollowersUIDGTE applies the GTE predicate on the "followers_uid" field.
func FollowersUIDGTE(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldGTE(FieldFollowersUID, v))
}

// FollowersUIDLT applies the LT predicate on the "followers_uid" field.
func FollowersUIDLT(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldLT(FieldFollowersUID, v))
}

// FollowersUIDLTE applies the LTE predicate on the "followers_uid" field.
func FollowersUIDLTE(v int32) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldLTE(FieldFollowersUID, v))
}

// FollowersUIDIsNil applies the IsNil predicate on the "followers_uid" field.
func FollowersUIDIsNil() predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldIsNull(FieldFollowersUID))
}

// FollowersUIDNotNil applies the NotNil predicate on the "followers_uid" field.
func FollowersUIDNotNil() predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldNotNull(FieldFollowersUID))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(sql.FieldLTE(FieldCreateTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RdRUserFollowers) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RdRUserFollowers) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RdRUserFollowers) predicate.RdRUserFollowers {
	return predicate.RdRUserFollowers(func(s *sql.Selector) {
		p(s.Not())
	})
}
