// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: v1/message.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageSystemClient is the client API for MessageSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageSystemClient interface {
	ChatHistory(ctx context.Context, in *ChatHistoryRequest, opts ...grpc.CallOption) (*ChatHistoryReply, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error)
}

type messageSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageSystemClient(cc grpc.ClientConnInterface) MessageSystemClient {
	return &messageSystemClient{cc}
}

func (c *messageSystemClient) ChatHistory(ctx context.Context, in *ChatHistoryRequest, opts ...grpc.CallOption) (*ChatHistoryReply, error) {
	out := new(ChatHistoryReply)
	err := c.cc.Invoke(ctx, "/message.v1.MessageSystem/ChatHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageSystemClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error) {
	out := new(SendMessageReply)
	err := c.cc.Invoke(ctx, "/message.v1.MessageSystem/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageSystemServer is the server API for MessageSystem service.
// All implementations must embed UnimplementedMessageSystemServer
// for forward compatibility
type MessageSystemServer interface {
	ChatHistory(context.Context, *ChatHistoryRequest) (*ChatHistoryReply, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
	mustEmbedUnimplementedMessageSystemServer()
}

// UnimplementedMessageSystemServer must be embedded to have forward compatible implementations.
type UnimplementedMessageSystemServer struct {
}

func (UnimplementedMessageSystemServer) ChatHistory(context.Context, *ChatHistoryRequest) (*ChatHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatHistory not implemented")
}
func (UnimplementedMessageSystemServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessageSystemServer) mustEmbedUnimplementedMessageSystemServer() {}

// UnsafeMessageSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageSystemServer will
// result in compilation errors.
type UnsafeMessageSystemServer interface {
	mustEmbedUnimplementedMessageSystemServer()
}

func RegisterMessageSystemServer(s grpc.ServiceRegistrar, srv MessageSystemServer) {
	s.RegisterService(&MessageSystem_ServiceDesc, srv)
}

func _MessageSystem_ChatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageSystemServer).ChatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.v1.MessageSystem/ChatHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageSystemServer).ChatHistory(ctx, req.(*ChatHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageSystem_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageSystemServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.v1.MessageSystem/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageSystemServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageSystem_ServiceDesc is the grpc.ServiceDesc for MessageSystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageSystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.v1.MessageSystem",
	HandlerType: (*MessageSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChatHistory",
			Handler:    _MessageSystem_ChatHistory_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _MessageSystem_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/message.proto",
}
