// Code generated by ent, DO NOT EDIT.

package rdmoment

import (
	"time"
)

const (
	// Label holds the string label denoting the rdmoment type in the database.
	Label = "rd_moment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldByUID holds the string denoting the by_uid field in the database.
	FieldByUID = "by_uid"
	// FieldTxt holds the string denoting the txt field in the database.
	FieldTxt = "txt"
	// FieldImgs holds the string denoting the imgs field in the database.
	FieldImgs = "imgs"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPublishTime holds the string denoting the publish_time field in the database.
	FieldPublishTime = "publish_time"
	// Table holds the table name of the rdmoment in the database.
	Table = "rd_moment"
)

// Columns holds all SQL columns for rdmoment fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldByUID,
	FieldTxt,
	FieldImgs,
	FieldStatus,
	FieldPublishTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType int32
	// DefaultPublishTime holds the default value on creation for the "publish_time" field.
	DefaultPublishTime func() time.Time
)
