// Code generated by ent, DO NOT EDIT.

package rdmoment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldLTE(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldEQ(FieldType, v))
}

// ByUID applies equality check predicate on the "by_uid" field. It's identical to ByUIDEQ.
func ByUID(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldEQ(FieldByUID, v))
}

// Txt applies equality check predicate on the "txt" field. It's identical to TxtEQ.
func Txt(v string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldEQ(FieldTxt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldEQ(FieldStatus, v))
}

// PublishTime applies equality check predicate on the "publish_time" field. It's identical to PublishTimeEQ.
func PublishTime(v time.Time) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldEQ(FieldPublishTime, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldLTE(FieldType, v))
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.RdMoment {
	return predicate.RdMoment(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNotNull(FieldType))
}

// ByUIDEQ applies the EQ predicate on the "by_uid" field.
func ByUIDEQ(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldEQ(FieldByUID, v))
}

// ByUIDNEQ applies the NEQ predicate on the "by_uid" field.
func ByUIDNEQ(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNEQ(FieldByUID, v))
}

// ByUIDIn applies the In predicate on the "by_uid" field.
func ByUIDIn(vs ...int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldIn(FieldByUID, vs...))
}

// ByUIDNotIn applies the NotIn predicate on the "by_uid" field.
func ByUIDNotIn(vs ...int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNotIn(FieldByUID, vs...))
}

// ByUIDGT applies the GT predicate on the "by_uid" field.
func ByUIDGT(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldGT(FieldByUID, v))
}

// ByUIDGTE applies the GTE predicate on the "by_uid" field.
func ByUIDGTE(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldGTE(FieldByUID, v))
}

// ByUIDLT applies the LT predicate on the "by_uid" field.
func ByUIDLT(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldLT(FieldByUID, v))
}

// ByUIDLTE applies the LTE predicate on the "by_uid" field.
func ByUIDLTE(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldLTE(FieldByUID, v))
}

// ByUIDIsNil applies the IsNil predicate on the "by_uid" field.
func ByUIDIsNil() predicate.RdMoment {
	return predicate.RdMoment(sql.FieldIsNull(FieldByUID))
}

// ByUIDNotNil applies the NotNil predicate on the "by_uid" field.
func ByUIDNotNil() predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNotNull(FieldByUID))
}

// TxtEQ applies the EQ predicate on the "txt" field.
func TxtEQ(v string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldEQ(FieldTxt, v))
}

// TxtNEQ applies the NEQ predicate on the "txt" field.
func TxtNEQ(v string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNEQ(FieldTxt, v))
}

// TxtIn applies the In predicate on the "txt" field.
func TxtIn(vs ...string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldIn(FieldTxt, vs...))
}

// TxtNotIn applies the NotIn predicate on the "txt" field.
func TxtNotIn(vs ...string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNotIn(FieldTxt, vs...))
}

// TxtGT applies the GT predicate on the "txt" field.
func TxtGT(v string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldGT(FieldTxt, v))
}

// TxtGTE applies the GTE predicate on the "txt" field.
func TxtGTE(v string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldGTE(FieldTxt, v))
}

// TxtLT applies the LT predicate on the "txt" field.
func TxtLT(v string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldLT(FieldTxt, v))
}

// TxtLTE applies the LTE predicate on the "txt" field.
func TxtLTE(v string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldLTE(FieldTxt, v))
}

// TxtContains applies the Contains predicate on the "txt" field.
func TxtContains(v string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldContains(FieldTxt, v))
}

// TxtHasPrefix applies the HasPrefix predicate on the "txt" field.
func TxtHasPrefix(v string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldHasPrefix(FieldTxt, v))
}

// TxtHasSuffix applies the HasSuffix predicate on the "txt" field.
func TxtHasSuffix(v string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldHasSuffix(FieldTxt, v))
}

// TxtEqualFold applies the EqualFold predicate on the "txt" field.
func TxtEqualFold(v string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldEqualFold(FieldTxt, v))
}

// TxtContainsFold applies the ContainsFold predicate on the "txt" field.
func TxtContainsFold(v string) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldContainsFold(FieldTxt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int32) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldLTE(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.RdMoment {
	return predicate.RdMoment(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNotNull(FieldStatus))
}

// PublishTimeEQ applies the EQ predicate on the "publish_time" field.
func PublishTimeEQ(v time.Time) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldEQ(FieldPublishTime, v))
}

// PublishTimeNEQ applies the NEQ predicate on the "publish_time" field.
func PublishTimeNEQ(v time.Time) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNEQ(FieldPublishTime, v))
}

// PublishTimeIn applies the In predicate on the "publish_time" field.
func PublishTimeIn(vs ...time.Time) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldIn(FieldPublishTime, vs...))
}

// PublishTimeNotIn applies the NotIn predicate on the "publish_time" field.
func PublishTimeNotIn(vs ...time.Time) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldNotIn(FieldPublishTime, vs...))
}

// PublishTimeGT applies the GT predicate on the "publish_time" field.
func PublishTimeGT(v time.Time) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldGT(FieldPublishTime, v))
}

// PublishTimeGTE applies the GTE predicate on the "publish_time" field.
func PublishTimeGTE(v time.Time) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldGTE(FieldPublishTime, v))
}

// PublishTimeLT applies the LT predicate on the "publish_time" field.
func PublishTimeLT(v time.Time) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldLT(FieldPublishTime, v))
}

// PublishTimeLTE applies the LTE predicate on the "publish_time" field.
func PublishTimeLTE(v time.Time) predicate.RdMoment {
	return predicate.RdMoment(sql.FieldLTE(FieldPublishTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RdMoment) predicate.RdMoment {
	return predicate.RdMoment(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RdMoment) predicate.RdMoment {
	return predicate.RdMoment(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RdMoment) predicate.RdMoment {
	return predicate.RdMoment(func(s *sql.Selector) {
		p(s.Not())
	})
}
