// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// RdMessage is the predicate function for rdmessage builders.
type RdMessage func(*sql.Selector)

// RdMoment is the predicate function for rdmoment builders.
type RdMoment func(*sql.Selector)

// RdRMomentsFollowing is the predicate function for rdrmomentsfollowing builders.
type RdRMomentsFollowing func(*sql.Selector)

// RdRUserFollowers is the predicate function for rdruserfollowers builders.
type RdRUserFollowers func(*sql.Selector)

// RdRUserFollowing is the predicate function for rdruserfollowing builders.
type RdRUserFollowing func(*sql.Selector)

// RdUser is the predicate function for rduser builders.
type RdUser func(*sql.Selector)
