// Code generated by ent, DO NOT EDIT.

package rdmessage

import (
	"time"
)

const (
	// Label holds the string label denoting the rdmessage type in the database.
	Label = "rd_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSenderUID holds the string denoting the sender_uid field in the database.
	FieldSenderUID = "sender_uid"
	// FieldRecverUID holds the string denoting the recver_uid field in the database.
	FieldRecverUID = "recver_uid"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// Table holds the table name of the rdmessage in the database.
	Table = "rd_message"
)

// Columns holds all SQL columns for rdmessage fields.
var Columns = []string{
	FieldID,
	FieldSenderUID,
	FieldRecverUID,
	FieldContent,
	FieldCreateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
)
