// Code generated by ent, DO NOT EDIT.

package rdrmomentsfollowing

import (
	"time"
)

const (
	// Label holds the string label denoting the rdrmomentsfollowing type in the database.
	Label = "rd_rmoments_following"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMomentID holds the string denoting the moment_id field in the database.
	FieldMomentID = "moment_id"
	// FieldMomentType holds the string denoting the moment_type field in the database.
	FieldMomentType = "moment_type"
	// FieldByUID holds the string denoting the by_uid field in the database.
	FieldByUID = "by_uid"
	// FieldForUID holds the string denoting the for_uid field in the database.
	FieldForUID = "for_uid"
	// FieldTxt holds the string denoting the txt field in the database.
	FieldTxt = "txt"
	// FieldImgs holds the string denoting the imgs field in the database.
	FieldImgs = "imgs"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPublishTime holds the string denoting the publish_time field in the database.
	FieldPublishTime = "publish_time"
	// Table holds the table name of the rdrmomentsfollowing in the database.
	Table = "rd_r_moments_following"
)

// Columns holds all SQL columns for rdrmomentsfollowing fields.
var Columns = []string{
	FieldID,
	FieldMomentID,
	FieldMomentType,
	FieldByUID,
	FieldForUID,
	FieldTxt,
	FieldImgs,
	FieldStatus,
	FieldPublishTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultMomentID holds the default value on creation for the "moment_id" field.
	DefaultMomentID int64
	// DefaultMomentType holds the default value on creation for the "moment_type" field.
	DefaultMomentType int32
	// DefaultPublishTime holds the default value on creation for the "publish_time" field.
	DefaultPublishTime func() time.Time
)
