// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"fxkt.tech/raiden/app/feed/service/internal/data/db/model"
	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newDynamicHistory(db *gorm.DB) dynamicHistory {
	_dynamicHistory := dynamicHistory{}

	_dynamicHistory.dynamicHistoryDo.UseDB(db)
	_dynamicHistory.dynamicHistoryDo.UseModel(&model.DynamicHistory{})

	tableName := _dynamicHistory.dynamicHistoryDo.TableName()
	_dynamicHistory.ALL = field.NewField(tableName, "*")
	_dynamicHistory.DmcID = field.NewInt64(tableName, "dmc_id")
	_dynamicHistory.DmcType = field.NewInt32(tableName, "dmc_type")
	_dynamicHistory.ByUID = field.NewInt32(tableName, "by_uid")
	_dynamicHistory.Txt = field.NewString(tableName, "txt")
	_dynamicHistory.Imgs = field.NewString(tableName, "imgs")
	_dynamicHistory.Status = field.NewInt32(tableName, "status")
	_dynamicHistory.PublishTime = field.NewTime(tableName, "publish_time")

	_dynamicHistory.fillFieldMap()

	return _dynamicHistory
}

type dynamicHistory struct {
	dynamicHistoryDo dynamicHistoryDo

	ALL         field.Field
	DmcID       field.Int64
	DmcType     field.Int32
	ByUID       field.Int32
	Txt         field.String
	Imgs        field.String
	Status      field.Int32
	PublishTime field.Time

	fieldMap map[string]field.Expr
}

func (d dynamicHistory) Table(newTableName string) *dynamicHistory {
	d.dynamicHistoryDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dynamicHistory) As(alias string) *dynamicHistory {
	d.dynamicHistoryDo.DO = *(d.dynamicHistoryDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dynamicHistory) updateTableName(table string) *dynamicHistory {
	d.ALL = field.NewField(table, "*")
	d.DmcID = field.NewInt64(table, "dmc_id")
	d.DmcType = field.NewInt32(table, "dmc_type")
	d.ByUID = field.NewInt32(table, "by_uid")
	d.Txt = field.NewString(table, "txt")
	d.Imgs = field.NewString(table, "imgs")
	d.Status = field.NewInt32(table, "status")
	d.PublishTime = field.NewTime(table, "publish_time")

	d.fillFieldMap()

	return d
}

func (d *dynamicHistory) WithContext(ctx context.Context) *dynamicHistoryDo {
	return d.dynamicHistoryDo.WithContext(ctx)
}

func (d dynamicHistory) TableName() string { return d.dynamicHistoryDo.TableName() }

func (d *dynamicHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dynamicHistory) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 7)
	d.fieldMap["dmc_id"] = d.DmcID
	d.fieldMap["dmc_type"] = d.DmcType
	d.fieldMap["by_uid"] = d.ByUID
	d.fieldMap["txt"] = d.Txt
	d.fieldMap["imgs"] = d.Imgs
	d.fieldMap["status"] = d.Status
	d.fieldMap["publish_time"] = d.PublishTime
}

func (d dynamicHistory) clone(db *gorm.DB) dynamicHistory {
	d.dynamicHistoryDo.ReplaceDB(db)
	return d
}

type dynamicHistoryDo struct{ gen.DO }

func (d dynamicHistoryDo) Debug() *dynamicHistoryDo {
	return d.withDO(d.DO.Debug())
}

func (d dynamicHistoryDo) WithContext(ctx context.Context) *dynamicHistoryDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dynamicHistoryDo) Clauses(conds ...clause.Expression) *dynamicHistoryDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dynamicHistoryDo) Returning(value interface{}, columns ...string) *dynamicHistoryDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dynamicHistoryDo) Not(conds ...gen.Condition) *dynamicHistoryDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dynamicHistoryDo) Or(conds ...gen.Condition) *dynamicHistoryDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dynamicHistoryDo) Select(conds ...field.Expr) *dynamicHistoryDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dynamicHistoryDo) Where(conds ...gen.Condition) *dynamicHistoryDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dynamicHistoryDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *dynamicHistoryDo {
	return d.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (d dynamicHistoryDo) Order(conds ...field.Expr) *dynamicHistoryDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dynamicHistoryDo) Distinct(cols ...field.Expr) *dynamicHistoryDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dynamicHistoryDo) Omit(cols ...field.Expr) *dynamicHistoryDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dynamicHistoryDo) Join(table schema.Tabler, on ...field.Expr) *dynamicHistoryDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dynamicHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *dynamicHistoryDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dynamicHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *dynamicHistoryDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dynamicHistoryDo) Group(cols ...field.Expr) *dynamicHistoryDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dynamicHistoryDo) Having(conds ...gen.Condition) *dynamicHistoryDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dynamicHistoryDo) Limit(limit int) *dynamicHistoryDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dynamicHistoryDo) Offset(offset int) *dynamicHistoryDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dynamicHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *dynamicHistoryDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dynamicHistoryDo) Unscoped() *dynamicHistoryDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dynamicHistoryDo) Create(values ...*model.DynamicHistory) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dynamicHistoryDo) CreateInBatches(values []*model.DynamicHistory, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dynamicHistoryDo) Save(values ...*model.DynamicHistory) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dynamicHistoryDo) First() (*model.DynamicHistory, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DynamicHistory), nil
	}
}

func (d dynamicHistoryDo) Take() (*model.DynamicHistory, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DynamicHistory), nil
	}
}

func (d dynamicHistoryDo) Last() (*model.DynamicHistory, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DynamicHistory), nil
	}
}

func (d dynamicHistoryDo) Find() ([]*model.DynamicHistory, error) {
	result, err := d.DO.Find()
	return result.([]*model.DynamicHistory), err
}

func (d dynamicHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DynamicHistory, err error) {
	buf := make([]*model.DynamicHistory, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dynamicHistoryDo) FindInBatches(result *[]*model.DynamicHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dynamicHistoryDo) Attrs(attrs ...field.AssignExpr) *dynamicHistoryDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dynamicHistoryDo) Assign(attrs ...field.AssignExpr) *dynamicHistoryDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dynamicHistoryDo) Joins(field field.RelationField) *dynamicHistoryDo {
	return d.withDO(d.DO.Joins(field))
}

func (d dynamicHistoryDo) Preload(field field.RelationField) *dynamicHistoryDo {
	return d.withDO(d.DO.Preload(field))
}

func (d dynamicHistoryDo) FirstOrInit() (*model.DynamicHistory, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DynamicHistory), nil
	}
}

func (d dynamicHistoryDo) FirstOrCreate() (*model.DynamicHistory, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DynamicHistory), nil
	}
}

func (d dynamicHistoryDo) FindByPage(offset int, limit int) (result []*model.DynamicHistory, count int64, err error) {
	if limit <= 0 {
		count, err = d.Count()
		return
	}

	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dynamicHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d *dynamicHistoryDo) withDO(do gen.Dao) *dynamicHistoryDo {
	d.DO = *do.(*gen.DO)
	return d
}
