// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/predicate"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/rdmessage"
)

// RdMessageDelete is the builder for deleting a RdMessage entity.
type RdMessageDelete struct {
	config
	hooks    []Hook
	mutation *RdMessageMutation
}

// Where appends a list predicates to the RdMessageDelete builder.
func (rmd *RdMessageDelete) Where(ps ...predicate.RdMessage) *RdMessageDelete {
	rmd.mutation.Where(ps...)
	return rmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rmd *RdMessageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, RdMessageMutation](ctx, rmd.sqlExec, rmd.mutation, rmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rmd *RdMessageDelete) ExecX(ctx context.Context) int {
	n, err := rmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rmd *RdMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: rdmessage.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: rdmessage.FieldID,
			},
		},
	}
	if ps := rmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rmd.mutation.done = true
	return affected, err
}

// RdMessageDeleteOne is the builder for deleting a single RdMessage entity.
type RdMessageDeleteOne struct {
	rmd *RdMessageDelete
}

// Exec executes the deletion query.
func (rmdo *RdMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := rmdo.rmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rdmessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rmdo *RdMessageDeleteOne) ExecX(ctx context.Context) {
	rmdo.rmd.ExecX(ctx)
}
