// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/predicate"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/rdmessage"
)

// RdMessageQuery is the builder for querying RdMessage entities.
type RdMessageQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.RdMessage
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RdMessageQuery builder.
func (rmq *RdMessageQuery) Where(ps ...predicate.RdMessage) *RdMessageQuery {
	rmq.predicates = append(rmq.predicates, ps...)
	return rmq
}

// Limit the number of records to be returned by this query.
func (rmq *RdMessageQuery) Limit(limit int) *RdMessageQuery {
	rmq.ctx.Limit = &limit
	return rmq
}

// Offset to start from.
func (rmq *RdMessageQuery) Offset(offset int) *RdMessageQuery {
	rmq.ctx.Offset = &offset
	return rmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rmq *RdMessageQuery) Unique(unique bool) *RdMessageQuery {
	rmq.ctx.Unique = &unique
	return rmq
}

// Order specifies how the records should be ordered.
func (rmq *RdMessageQuery) Order(o ...OrderFunc) *RdMessageQuery {
	rmq.order = append(rmq.order, o...)
	return rmq
}

// First returns the first RdMessage entity from the query.
// Returns a *NotFoundError when no RdMessage was found.
func (rmq *RdMessageQuery) First(ctx context.Context) (*RdMessage, error) {
	nodes, err := rmq.Limit(1).All(setContextOp(ctx, rmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rdmessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rmq *RdMessageQuery) FirstX(ctx context.Context) *RdMessage {
	node, err := rmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RdMessage ID from the query.
// Returns a *NotFoundError when no RdMessage ID was found.
func (rmq *RdMessageQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = rmq.Limit(1).IDs(setContextOp(ctx, rmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rdmessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rmq *RdMessageQuery) FirstIDX(ctx context.Context) int32 {
	id, err := rmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RdMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RdMessage entity is found.
// Returns a *NotFoundError when no RdMessage entities are found.
func (rmq *RdMessageQuery) Only(ctx context.Context) (*RdMessage, error) {
	nodes, err := rmq.Limit(2).All(setContextOp(ctx, rmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rdmessage.Label}
	default:
		return nil, &NotSingularError{rdmessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rmq *RdMessageQuery) OnlyX(ctx context.Context) *RdMessage {
	node, err := rmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RdMessage ID in the query.
// Returns a *NotSingularError when more than one RdMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (rmq *RdMessageQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = rmq.Limit(2).IDs(setContextOp(ctx, rmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rdmessage.Label}
	default:
		err = &NotSingularError{rdmessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rmq *RdMessageQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := rmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RdMessages.
func (rmq *RdMessageQuery) All(ctx context.Context) ([]*RdMessage, error) {
	ctx = setContextOp(ctx, rmq.ctx, "All")
	if err := rmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RdMessage, *RdMessageQuery]()
	return withInterceptors[[]*RdMessage](ctx, rmq, qr, rmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rmq *RdMessageQuery) AllX(ctx context.Context) []*RdMessage {
	nodes, err := rmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RdMessage IDs.
func (rmq *RdMessageQuery) IDs(ctx context.Context) ([]int32, error) {
	var ids []int32
	ctx = setContextOp(ctx, rmq.ctx, "IDs")
	if err := rmq.Select(rdmessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rmq *RdMessageQuery) IDsX(ctx context.Context) []int32 {
	ids, err := rmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rmq *RdMessageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rmq.ctx, "Count")
	if err := rmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rmq, querierCount[*RdMessageQuery](), rmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rmq *RdMessageQuery) CountX(ctx context.Context) int {
	count, err := rmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rmq *RdMessageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rmq.ctx, "Exist")
	switch _, err := rmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rmq *RdMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := rmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RdMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rmq *RdMessageQuery) Clone() *RdMessageQuery {
	if rmq == nil {
		return nil
	}
	return &RdMessageQuery{
		config:     rmq.config,
		ctx:        rmq.ctx.Clone(),
		order:      append([]OrderFunc{}, rmq.order...),
		inters:     append([]Interceptor{}, rmq.inters...),
		predicates: append([]predicate.RdMessage{}, rmq.predicates...),
		// clone intermediate query.
		sql:  rmq.sql.Clone(),
		path: rmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SenderUID int32 `json:"sender_uid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RdMessage.Query().
//		GroupBy(rdmessage.FieldSenderUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rmq *RdMessageQuery) GroupBy(field string, fields ...string) *RdMessageGroupBy {
	rmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RdMessageGroupBy{build: rmq}
	grbuild.flds = &rmq.ctx.Fields
	grbuild.label = rdmessage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SenderUID int32 `json:"sender_uid,omitempty"`
//	}
//
//	client.RdMessage.Query().
//		Select(rdmessage.FieldSenderUID).
//		Scan(ctx, &v)
func (rmq *RdMessageQuery) Select(fields ...string) *RdMessageSelect {
	rmq.ctx.Fields = append(rmq.ctx.Fields, fields...)
	sbuild := &RdMessageSelect{RdMessageQuery: rmq}
	sbuild.label = rdmessage.Label
	sbuild.flds, sbuild.scan = &rmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RdMessageSelect configured with the given aggregations.
func (rmq *RdMessageQuery) Aggregate(fns ...AggregateFunc) *RdMessageSelect {
	return rmq.Select().Aggregate(fns...)
}

func (rmq *RdMessageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rmq); err != nil {
				return err
			}
		}
	}
	for _, f := range rmq.ctx.Fields {
		if !rdmessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rmq.path != nil {
		prev, err := rmq.path(ctx)
		if err != nil {
			return err
		}
		rmq.sql = prev
	}
	return nil
}

func (rmq *RdMessageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RdMessage, error) {
	var (
		nodes = []*RdMessage{}
		_spec = rmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RdMessage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RdMessage{config: rmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rmq *RdMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rmq.querySpec()
	_spec.Node.Columns = rmq.ctx.Fields
	if len(rmq.ctx.Fields) > 0 {
		_spec.Unique = rmq.ctx.Unique != nil && *rmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rmq.driver, _spec)
}

func (rmq *RdMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   rdmessage.Table,
			Columns: rdmessage.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: rdmessage.FieldID,
			},
		},
		From:   rmq.sql,
		Unique: true,
	}
	if unique := rmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rdmessage.FieldID)
		for i := range fields {
			if fields[i] != rdmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rmq *RdMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rmq.driver.Dialect())
	t1 := builder.Table(rdmessage.Table)
	columns := rmq.ctx.Fields
	if len(columns) == 0 {
		columns = rdmessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rmq.sql != nil {
		selector = rmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rmq.ctx.Unique != nil && *rmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rmq.predicates {
		p(selector)
	}
	for _, p := range rmq.order {
		p(selector)
	}
	if offset := rmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RdMessageGroupBy is the group-by builder for RdMessage entities.
type RdMessageGroupBy struct {
	selector
	build *RdMessageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rmgb *RdMessageGroupBy) Aggregate(fns ...AggregateFunc) *RdMessageGroupBy {
	rmgb.fns = append(rmgb.fns, fns...)
	return rmgb
}

// Scan applies the selector query and scans the result into the given value.
func (rmgb *RdMessageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rmgb.build.ctx, "GroupBy")
	if err := rmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RdMessageQuery, *RdMessageGroupBy](ctx, rmgb.build, rmgb, rmgb.build.inters, v)
}

func (rmgb *RdMessageGroupBy) sqlScan(ctx context.Context, root *RdMessageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rmgb.fns))
	for _, fn := range rmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rmgb.flds)+len(rmgb.fns))
		for _, f := range *rmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RdMessageSelect is the builder for selecting fields of RdMessage entities.
type RdMessageSelect struct {
	*RdMessageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rms *RdMessageSelect) Aggregate(fns ...AggregateFunc) *RdMessageSelect {
	rms.fns = append(rms.fns, fns...)
	return rms
}

// Scan applies the selector query and scans the result into the given value.
func (rms *RdMessageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rms.ctx, "Select")
	if err := rms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RdMessageQuery, *RdMessageSelect](ctx, rms.RdMessageQuery, rms, rms.inters, v)
}

func (rms *RdMessageSelect) sqlScan(ctx context.Context, root *RdMessageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rms.fns))
	for _, fn := range rms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
