// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/rdrmomentsfollowing"
)

// RdRMomentsFollowingCreate is the builder for creating a RdRMomentsFollowing entity.
type RdRMomentsFollowingCreate struct {
	config
	mutation *RdRMomentsFollowingMutation
	hooks    []Hook
}

// SetMomentID sets the "moment_id" field.
func (rrfc *RdRMomentsFollowingCreate) SetMomentID(i int64) *RdRMomentsFollowingCreate {
	rrfc.mutation.SetMomentID(i)
	return rrfc
}

// SetNillableMomentID sets the "moment_id" field if the given value is not nil.
func (rrfc *RdRMomentsFollowingCreate) SetNillableMomentID(i *int64) *RdRMomentsFollowingCreate {
	if i != nil {
		rrfc.SetMomentID(*i)
	}
	return rrfc
}

// SetMomentType sets the "moment_type" field.
func (rrfc *RdRMomentsFollowingCreate) SetMomentType(i int32) *RdRMomentsFollowingCreate {
	rrfc.mutation.SetMomentType(i)
	return rrfc
}

// SetNillableMomentType sets the "moment_type" field if the given value is not nil.
func (rrfc *RdRMomentsFollowingCreate) SetNillableMomentType(i *int32) *RdRMomentsFollowingCreate {
	if i != nil {
		rrfc.SetMomentType(*i)
	}
	return rrfc
}

// SetByUID sets the "by_uid" field.
func (rrfc *RdRMomentsFollowingCreate) SetByUID(i int32) *RdRMomentsFollowingCreate {
	rrfc.mutation.SetByUID(i)
	return rrfc
}

// SetNillableByUID sets the "by_uid" field if the given value is not nil.
func (rrfc *RdRMomentsFollowingCreate) SetNillableByUID(i *int32) *RdRMomentsFollowingCreate {
	if i != nil {
		rrfc.SetByUID(*i)
	}
	return rrfc
}

// SetForUID sets the "for_uid" field.
func (rrfc *RdRMomentsFollowingCreate) SetForUID(i int32) *RdRMomentsFollowingCreate {
	rrfc.mutation.SetForUID(i)
	return rrfc
}

// SetNillableForUID sets the "for_uid" field if the given value is not nil.
func (rrfc *RdRMomentsFollowingCreate) SetNillableForUID(i *int32) *RdRMomentsFollowingCreate {
	if i != nil {
		rrfc.SetForUID(*i)
	}
	return rrfc
}

// SetTxt sets the "txt" field.
func (rrfc *RdRMomentsFollowingCreate) SetTxt(s string) *RdRMomentsFollowingCreate {
	rrfc.mutation.SetTxt(s)
	return rrfc
}

// SetImgs sets the "imgs" field.
func (rrfc *RdRMomentsFollowingCreate) SetImgs(s []string) *RdRMomentsFollowingCreate {
	rrfc.mutation.SetImgs(s)
	return rrfc
}

// SetStatus sets the "status" field.
func (rrfc *RdRMomentsFollowingCreate) SetStatus(i int32) *RdRMomentsFollowingCreate {
	rrfc.mutation.SetStatus(i)
	return rrfc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rrfc *RdRMomentsFollowingCreate) SetNillableStatus(i *int32) *RdRMomentsFollowingCreate {
	if i != nil {
		rrfc.SetStatus(*i)
	}
	return rrfc
}

// SetPublishTime sets the "publish_time" field.
func (rrfc *RdRMomentsFollowingCreate) SetPublishTime(t time.Time) *RdRMomentsFollowingCreate {
	rrfc.mutation.SetPublishTime(t)
	return rrfc
}

// SetNillablePublishTime sets the "publish_time" field if the given value is not nil.
func (rrfc *RdRMomentsFollowingCreate) SetNillablePublishTime(t *time.Time) *RdRMomentsFollowingCreate {
	if t != nil {
		rrfc.SetPublishTime(*t)
	}
	return rrfc
}

// SetID sets the "id" field.
func (rrfc *RdRMomentsFollowingCreate) SetID(i int64) *RdRMomentsFollowingCreate {
	rrfc.mutation.SetID(i)
	return rrfc
}

// Mutation returns the RdRMomentsFollowingMutation object of the builder.
func (rrfc *RdRMomentsFollowingCreate) Mutation() *RdRMomentsFollowingMutation {
	return rrfc.mutation
}

// Save creates the RdRMomentsFollowing in the database.
func (rrfc *RdRMomentsFollowingCreate) Save(ctx context.Context) (*RdRMomentsFollowing, error) {
	rrfc.defaults()
	return withHooks[*RdRMomentsFollowing, RdRMomentsFollowingMutation](ctx, rrfc.sqlSave, rrfc.mutation, rrfc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rrfc *RdRMomentsFollowingCreate) SaveX(ctx context.Context) *RdRMomentsFollowing {
	v, err := rrfc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rrfc *RdRMomentsFollowingCreate) Exec(ctx context.Context) error {
	_, err := rrfc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rrfc *RdRMomentsFollowingCreate) ExecX(ctx context.Context) {
	if err := rrfc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rrfc *RdRMomentsFollowingCreate) defaults() {
	if _, ok := rrfc.mutation.MomentID(); !ok {
		v := rdrmomentsfollowing.DefaultMomentID
		rrfc.mutation.SetMomentID(v)
	}
	if _, ok := rrfc.mutation.MomentType(); !ok {
		v := rdrmomentsfollowing.DefaultMomentType
		rrfc.mutation.SetMomentType(v)
	}
	if _, ok := rrfc.mutation.PublishTime(); !ok {
		v := rdrmomentsfollowing.DefaultPublishTime()
		rrfc.mutation.SetPublishTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rrfc *RdRMomentsFollowingCreate) check() error {
	if _, ok := rrfc.mutation.Txt(); !ok {
		return &ValidationError{Name: "txt", err: errors.New(`ent: missing required field "RdRMomentsFollowing.txt"`)}
	}
	if _, ok := rrfc.mutation.Imgs(); !ok {
		return &ValidationError{Name: "imgs", err: errors.New(`ent: missing required field "RdRMomentsFollowing.imgs"`)}
	}
	if _, ok := rrfc.mutation.PublishTime(); !ok {
		return &ValidationError{Name: "publish_time", err: errors.New(`ent: missing required field "RdRMomentsFollowing.publish_time"`)}
	}
	return nil
}

func (rrfc *RdRMomentsFollowingCreate) sqlSave(ctx context.Context) (*RdRMomentsFollowing, error) {
	if err := rrfc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rrfc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rrfc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	rrfc.mutation.id = &_node.ID
	rrfc.mutation.done = true
	return _node, nil
}

func (rrfc *RdRMomentsFollowingCreate) createSpec() (*RdRMomentsFollowing, *sqlgraph.CreateSpec) {
	var (
		_node = &RdRMomentsFollowing{config: rrfc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: rdrmomentsfollowing.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: rdrmomentsfollowing.FieldID,
			},
		}
	)
	if id, ok := rrfc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rrfc.mutation.MomentID(); ok {
		_spec.SetField(rdrmomentsfollowing.FieldMomentID, field.TypeInt64, value)
		_node.MomentID = value
	}
	if value, ok := rrfc.mutation.MomentType(); ok {
		_spec.SetField(rdrmomentsfollowing.FieldMomentType, field.TypeInt32, value)
		_node.MomentType = value
	}
	if value, ok := rrfc.mutation.ByUID(); ok {
		_spec.SetField(rdrmomentsfollowing.FieldByUID, field.TypeInt32, value)
		_node.ByUID = value
	}
	if value, ok := rrfc.mutation.ForUID(); ok {
		_spec.SetField(rdrmomentsfollowing.FieldForUID, field.TypeInt32, value)
		_node.ForUID = value
	}
	if value, ok := rrfc.mutation.Txt(); ok {
		_spec.SetField(rdrmomentsfollowing.FieldTxt, field.TypeString, value)
		_node.Txt = value
	}
	if value, ok := rrfc.mutation.Imgs(); ok {
		_spec.SetField(rdrmomentsfollowing.FieldImgs, field.TypeJSON, value)
		_node.Imgs = value
	}
	if value, ok := rrfc.mutation.Status(); ok {
		_spec.SetField(rdrmomentsfollowing.FieldStatus, field.TypeInt32, value)
		_node.Status = value
	}
	if value, ok := rrfc.mutation.PublishTime(); ok {
		_spec.SetField(rdrmomentsfollowing.FieldPublishTime, field.TypeTime, value)
		_node.PublishTime = value
	}
	return _node, _spec
}

// RdRMomentsFollowingCreateBulk is the builder for creating many RdRMomentsFollowing entities in bulk.
type RdRMomentsFollowingCreateBulk struct {
	config
	builders []*RdRMomentsFollowingCreate
}

// Save creates the RdRMomentsFollowing entities in the database.
func (rrfcb *RdRMomentsFollowingCreateBulk) Save(ctx context.Context) ([]*RdRMomentsFollowing, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rrfcb.builders))
	nodes := make([]*RdRMomentsFollowing, len(rrfcb.builders))
	mutators := make([]Mutator, len(rrfcb.builders))
	for i := range rrfcb.builders {
		func(i int, root context.Context) {
			builder := rrfcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RdRMomentsFollowingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rrfcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rrfcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rrfcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rrfcb *RdRMomentsFollowingCreateBulk) SaveX(ctx context.Context) []*RdRMomentsFollowing {
	v, err := rrfcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rrfcb *RdRMomentsFollowingCreateBulk) Exec(ctx context.Context) error {
	_, err := rrfcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rrfcb *RdRMomentsFollowingCreateBulk) ExecX(ctx context.Context) {
	if err := rrfcb.Exec(ctx); err != nil {
		panic(err)
	}
}
