// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/rdruserfollowing"
)

// RdRUserFollowing is the model entity for the RdRUserFollowing schema.
type RdRUserFollowing struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// uid
	UID int32 `json:"uid,omitempty"`
	// 关注的人uid
	FollowingUID int32 `json:"following_uid,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RdRUserFollowing) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rdruserfollowing.FieldID, rdruserfollowing.FieldUID, rdruserfollowing.FieldFollowingUID:
			values[i] = new(sql.NullInt64)
		case rdruserfollowing.FieldCreateTime:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type RdRUserFollowing", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RdRUserFollowing fields.
func (rrf *RdRUserFollowing) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rdruserfollowing.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rrf.ID = int64(value.Int64)
		case rdruserfollowing.FieldUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				rrf.UID = int32(value.Int64)
			}
		case rdruserfollowing.FieldFollowingUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field following_uid", values[i])
			} else if value.Valid {
				rrf.FollowingUID = int32(value.Int64)
			}
		case rdruserfollowing.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				rrf.CreateTime = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this RdRUserFollowing.
// Note that you need to call RdRUserFollowing.Unwrap() before calling this method if this RdRUserFollowing
// was returned from a transaction, and the transaction was committed or rolled back.
func (rrf *RdRUserFollowing) Update() *RdRUserFollowingUpdateOne {
	return NewRdRUserFollowingClient(rrf.config).UpdateOne(rrf)
}

// Unwrap unwraps the RdRUserFollowing entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rrf *RdRUserFollowing) Unwrap() *RdRUserFollowing {
	_tx, ok := rrf.config.driver.(*txDriver)
	if !ok {
		panic("ent: RdRUserFollowing is not a transactional entity")
	}
	rrf.config.driver = _tx.drv
	return rrf
}

// String implements the fmt.Stringer.
func (rrf *RdRUserFollowing) String() string {
	var builder strings.Builder
	builder.WriteString("RdRUserFollowing(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rrf.ID))
	builder.WriteString("uid=")
	builder.WriteString(fmt.Sprintf("%v", rrf.UID))
	builder.WriteString(", ")
	builder.WriteString("following_uid=")
	builder.WriteString(fmt.Sprintf("%v", rrf.FollowingUID))
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(rrf.CreateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RdRUserFollowings is a parsable slice of RdRUserFollowing.
type RdRUserFollowings []*RdRUserFollowing

func (rrf RdRUserFollowings) config(cfg config) {
	for _i := range rrf {
		rrf[_i].config = cfg
	}
}
