// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/predicate"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/rdruserfollowers"
)

// RdRUserFollowersDelete is the builder for deleting a RdRUserFollowers entity.
type RdRUserFollowersDelete struct {
	config
	hooks    []Hook
	mutation *RdRUserFollowersMutation
}

// Where appends a list predicates to the RdRUserFollowersDelete builder.
func (rrfd *RdRUserFollowersDelete) Where(ps ...predicate.RdRUserFollowers) *RdRUserFollowersDelete {
	rrfd.mutation.Where(ps...)
	return rrfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rrfd *RdRUserFollowersDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, RdRUserFollowersMutation](ctx, rrfd.sqlExec, rrfd.mutation, rrfd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rrfd *RdRUserFollowersDelete) ExecX(ctx context.Context) int {
	n, err := rrfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rrfd *RdRUserFollowersDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: rdruserfollowers.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: rdruserfollowers.FieldID,
			},
		},
	}
	if ps := rrfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rrfd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rrfd.mutation.done = true
	return affected, err
}

// RdRUserFollowersDeleteOne is the builder for deleting a single RdRUserFollowers entity.
type RdRUserFollowersDeleteOne struct {
	rrfd *RdRUserFollowersDelete
}

// Exec executes the deletion query.
func (rrfdo *RdRUserFollowersDeleteOne) Exec(ctx context.Context) error {
	n, err := rrfdo.rrfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rdruserfollowers.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rrfdo *RdRUserFollowersDeleteOne) ExecX(ctx context.Context) {
	rrfdo.rrfd.ExecX(ctx)
}
