// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/predicate"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/rdruserfollowing"
)

// RdRUserFollowingUpdate is the builder for updating RdRUserFollowing entities.
type RdRUserFollowingUpdate struct {
	config
	hooks    []Hook
	mutation *RdRUserFollowingMutation
}

// Where appends a list predicates to the RdRUserFollowingUpdate builder.
func (rrfu *RdRUserFollowingUpdate) Where(ps ...predicate.RdRUserFollowing) *RdRUserFollowingUpdate {
	rrfu.mutation.Where(ps...)
	return rrfu
}

// SetUID sets the "uid" field.
func (rrfu *RdRUserFollowingUpdate) SetUID(i int32) *RdRUserFollowingUpdate {
	rrfu.mutation.ResetUID()
	rrfu.mutation.SetUID(i)
	return rrfu
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (rrfu *RdRUserFollowingUpdate) SetNillableUID(i *int32) *RdRUserFollowingUpdate {
	if i != nil {
		rrfu.SetUID(*i)
	}
	return rrfu
}

// AddUID adds i to the "uid" field.
func (rrfu *RdRUserFollowingUpdate) AddUID(i int32) *RdRUserFollowingUpdate {
	rrfu.mutation.AddUID(i)
	return rrfu
}

// ClearUID clears the value of the "uid" field.
func (rrfu *RdRUserFollowingUpdate) ClearUID() *RdRUserFollowingUpdate {
	rrfu.mutation.ClearUID()
	return rrfu
}

// SetFollowingUID sets the "following_uid" field.
func (rrfu *RdRUserFollowingUpdate) SetFollowingUID(i int32) *RdRUserFollowingUpdate {
	rrfu.mutation.ResetFollowingUID()
	rrfu.mutation.SetFollowingUID(i)
	return rrfu
}

// SetNillableFollowingUID sets the "following_uid" field if the given value is not nil.
func (rrfu *RdRUserFollowingUpdate) SetNillableFollowingUID(i *int32) *RdRUserFollowingUpdate {
	if i != nil {
		rrfu.SetFollowingUID(*i)
	}
	return rrfu
}

// AddFollowingUID adds i to the "following_uid" field.
func (rrfu *RdRUserFollowingUpdate) AddFollowingUID(i int32) *RdRUserFollowingUpdate {
	rrfu.mutation.AddFollowingUID(i)
	return rrfu
}

// ClearFollowingUID clears the value of the "following_uid" field.
func (rrfu *RdRUserFollowingUpdate) ClearFollowingUID() *RdRUserFollowingUpdate {
	rrfu.mutation.ClearFollowingUID()
	return rrfu
}

// SetCreateTime sets the "create_time" field.
func (rrfu *RdRUserFollowingUpdate) SetCreateTime(t time.Time) *RdRUserFollowingUpdate {
	rrfu.mutation.SetCreateTime(t)
	return rrfu
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (rrfu *RdRUserFollowingUpdate) SetNillableCreateTime(t *time.Time) *RdRUserFollowingUpdate {
	if t != nil {
		rrfu.SetCreateTime(*t)
	}
	return rrfu
}

// Mutation returns the RdRUserFollowingMutation object of the builder.
func (rrfu *RdRUserFollowingUpdate) Mutation() *RdRUserFollowingMutation {
	return rrfu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rrfu *RdRUserFollowingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, RdRUserFollowingMutation](ctx, rrfu.sqlSave, rrfu.mutation, rrfu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rrfu *RdRUserFollowingUpdate) SaveX(ctx context.Context) int {
	affected, err := rrfu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rrfu *RdRUserFollowingUpdate) Exec(ctx context.Context) error {
	_, err := rrfu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rrfu *RdRUserFollowingUpdate) ExecX(ctx context.Context) {
	if err := rrfu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rrfu *RdRUserFollowingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   rdruserfollowing.Table,
			Columns: rdruserfollowing.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: rdruserfollowing.FieldID,
			},
		},
	}
	if ps := rrfu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rrfu.mutation.UID(); ok {
		_spec.SetField(rdruserfollowing.FieldUID, field.TypeInt32, value)
	}
	if value, ok := rrfu.mutation.AddedUID(); ok {
		_spec.AddField(rdruserfollowing.FieldUID, field.TypeInt32, value)
	}
	if rrfu.mutation.UIDCleared() {
		_spec.ClearField(rdruserfollowing.FieldUID, field.TypeInt32)
	}
	if value, ok := rrfu.mutation.FollowingUID(); ok {
		_spec.SetField(rdruserfollowing.FieldFollowingUID, field.TypeInt32, value)
	}
	if value, ok := rrfu.mutation.AddedFollowingUID(); ok {
		_spec.AddField(rdruserfollowing.FieldFollowingUID, field.TypeInt32, value)
	}
	if rrfu.mutation.FollowingUIDCleared() {
		_spec.ClearField(rdruserfollowing.FieldFollowingUID, field.TypeInt32)
	}
	if value, ok := rrfu.mutation.CreateTime(); ok {
		_spec.SetField(rdruserfollowing.FieldCreateTime, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rrfu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rdruserfollowing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rrfu.mutation.done = true
	return n, nil
}

// RdRUserFollowingUpdateOne is the builder for updating a single RdRUserFollowing entity.
type RdRUserFollowingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RdRUserFollowingMutation
}

// SetUID sets the "uid" field.
func (rrfuo *RdRUserFollowingUpdateOne) SetUID(i int32) *RdRUserFollowingUpdateOne {
	rrfuo.mutation.ResetUID()
	rrfuo.mutation.SetUID(i)
	return rrfuo
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (rrfuo *RdRUserFollowingUpdateOne) SetNillableUID(i *int32) *RdRUserFollowingUpdateOne {
	if i != nil {
		rrfuo.SetUID(*i)
	}
	return rrfuo
}

// AddUID adds i to the "uid" field.
func (rrfuo *RdRUserFollowingUpdateOne) AddUID(i int32) *RdRUserFollowingUpdateOne {
	rrfuo.mutation.AddUID(i)
	return rrfuo
}

// ClearUID clears the value of the "uid" field.
func (rrfuo *RdRUserFollowingUpdateOne) ClearUID() *RdRUserFollowingUpdateOne {
	rrfuo.mutation.ClearUID()
	return rrfuo
}

// SetFollowingUID sets the "following_uid" field.
func (rrfuo *RdRUserFollowingUpdateOne) SetFollowingUID(i int32) *RdRUserFollowingUpdateOne {
	rrfuo.mutation.ResetFollowingUID()
	rrfuo.mutation.SetFollowingUID(i)
	return rrfuo
}

// SetNillableFollowingUID sets the "following_uid" field if the given value is not nil.
func (rrfuo *RdRUserFollowingUpdateOne) SetNillableFollowingUID(i *int32) *RdRUserFollowingUpdateOne {
	if i != nil {
		rrfuo.SetFollowingUID(*i)
	}
	return rrfuo
}

// AddFollowingUID adds i to the "following_uid" field.
func (rrfuo *RdRUserFollowingUpdateOne) AddFollowingUID(i int32) *RdRUserFollowingUpdateOne {
	rrfuo.mutation.AddFollowingUID(i)
	return rrfuo
}

// ClearFollowingUID clears the value of the "following_uid" field.
func (rrfuo *RdRUserFollowingUpdateOne) ClearFollowingUID() *RdRUserFollowingUpdateOne {
	rrfuo.mutation.ClearFollowingUID()
	return rrfuo
}

// SetCreateTime sets the "create_time" field.
func (rrfuo *RdRUserFollowingUpdateOne) SetCreateTime(t time.Time) *RdRUserFollowingUpdateOne {
	rrfuo.mutation.SetCreateTime(t)
	return rrfuo
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (rrfuo *RdRUserFollowingUpdateOne) SetNillableCreateTime(t *time.Time) *RdRUserFollowingUpdateOne {
	if t != nil {
		rrfuo.SetCreateTime(*t)
	}
	return rrfuo
}

// Mutation returns the RdRUserFollowingMutation object of the builder.
func (rrfuo *RdRUserFollowingUpdateOne) Mutation() *RdRUserFollowingMutation {
	return rrfuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rrfuo *RdRUserFollowingUpdateOne) Select(field string, fields ...string) *RdRUserFollowingUpdateOne {
	rrfuo.fields = append([]string{field}, fields...)
	return rrfuo
}

// Save executes the query and returns the updated RdRUserFollowing entity.
func (rrfuo *RdRUserFollowingUpdateOne) Save(ctx context.Context) (*RdRUserFollowing, error) {
	return withHooks[*RdRUserFollowing, RdRUserFollowingMutation](ctx, rrfuo.sqlSave, rrfuo.mutation, rrfuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rrfuo *RdRUserFollowingUpdateOne) SaveX(ctx context.Context) *RdRUserFollowing {
	node, err := rrfuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rrfuo *RdRUserFollowingUpdateOne) Exec(ctx context.Context) error {
	_, err := rrfuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rrfuo *RdRUserFollowingUpdateOne) ExecX(ctx context.Context) {
	if err := rrfuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rrfuo *RdRUserFollowingUpdateOne) sqlSave(ctx context.Context) (_node *RdRUserFollowing, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   rdruserfollowing.Table,
			Columns: rdruserfollowing.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: rdruserfollowing.FieldID,
			},
		},
	}
	id, ok := rrfuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RdRUserFollowing.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rrfuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rdruserfollowing.FieldID)
		for _, f := range fields {
			if !rdruserfollowing.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rdruserfollowing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rrfuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rrfuo.mutation.UID(); ok {
		_spec.SetField(rdruserfollowing.FieldUID, field.TypeInt32, value)
	}
	if value, ok := rrfuo.mutation.AddedUID(); ok {
		_spec.AddField(rdruserfollowing.FieldUID, field.TypeInt32, value)
	}
	if rrfuo.mutation.UIDCleared() {
		_spec.ClearField(rdruserfollowing.FieldUID, field.TypeInt32)
	}
	if value, ok := rrfuo.mutation.FollowingUID(); ok {
		_spec.SetField(rdruserfollowing.FieldFollowingUID, field.TypeInt32, value)
	}
	if value, ok := rrfuo.mutation.AddedFollowingUID(); ok {
		_spec.AddField(rdruserfollowing.FieldFollowingUID, field.TypeInt32, value)
	}
	if rrfuo.mutation.FollowingUIDCleared() {
		_spec.ClearField(rdruserfollowing.FieldFollowingUID, field.TypeInt32)
	}
	if value, ok := rrfuo.mutation.CreateTime(); ok {
		_spec.SetField(rdruserfollowing.FieldCreateTime, field.TypeTime, value)
	}
	_node = &RdRUserFollowing{config: rrfuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rrfuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rdruserfollowing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rrfuo.mutation.done = true
	return _node, nil
}
