// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/predicate"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/rdruserfollowers"
)

// RdRUserFollowersQuery is the builder for querying RdRUserFollowers entities.
type RdRUserFollowersQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.RdRUserFollowers
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RdRUserFollowersQuery builder.
func (rrfq *RdRUserFollowersQuery) Where(ps ...predicate.RdRUserFollowers) *RdRUserFollowersQuery {
	rrfq.predicates = append(rrfq.predicates, ps...)
	return rrfq
}

// Limit the number of records to be returned by this query.
func (rrfq *RdRUserFollowersQuery) Limit(limit int) *RdRUserFollowersQuery {
	rrfq.ctx.Limit = &limit
	return rrfq
}

// Offset to start from.
func (rrfq *RdRUserFollowersQuery) Offset(offset int) *RdRUserFollowersQuery {
	rrfq.ctx.Offset = &offset
	return rrfq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rrfq *RdRUserFollowersQuery) Unique(unique bool) *RdRUserFollowersQuery {
	rrfq.ctx.Unique = &unique
	return rrfq
}

// Order specifies how the records should be ordered.
func (rrfq *RdRUserFollowersQuery) Order(o ...OrderFunc) *RdRUserFollowersQuery {
	rrfq.order = append(rrfq.order, o...)
	return rrfq
}

// First returns the first RdRUserFollowers entity from the query.
// Returns a *NotFoundError when no RdRUserFollowers was found.
func (rrfq *RdRUserFollowersQuery) First(ctx context.Context) (*RdRUserFollowers, error) {
	nodes, err := rrfq.Limit(1).All(setContextOp(ctx, rrfq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rdruserfollowers.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rrfq *RdRUserFollowersQuery) FirstX(ctx context.Context) *RdRUserFollowers {
	node, err := rrfq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RdRUserFollowers ID from the query.
// Returns a *NotFoundError when no RdRUserFollowers ID was found.
func (rrfq *RdRUserFollowersQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = rrfq.Limit(1).IDs(setContextOp(ctx, rrfq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rdruserfollowers.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rrfq *RdRUserFollowersQuery) FirstIDX(ctx context.Context) int64 {
	id, err := rrfq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RdRUserFollowers entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RdRUserFollowers entity is found.
// Returns a *NotFoundError when no RdRUserFollowers entities are found.
func (rrfq *RdRUserFollowersQuery) Only(ctx context.Context) (*RdRUserFollowers, error) {
	nodes, err := rrfq.Limit(2).All(setContextOp(ctx, rrfq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rdruserfollowers.Label}
	default:
		return nil, &NotSingularError{rdruserfollowers.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rrfq *RdRUserFollowersQuery) OnlyX(ctx context.Context) *RdRUserFollowers {
	node, err := rrfq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RdRUserFollowers ID in the query.
// Returns a *NotSingularError when more than one RdRUserFollowers ID is found.
// Returns a *NotFoundError when no entities are found.
func (rrfq *RdRUserFollowersQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = rrfq.Limit(2).IDs(setContextOp(ctx, rrfq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rdruserfollowers.Label}
	default:
		err = &NotSingularError{rdruserfollowers.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rrfq *RdRUserFollowersQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := rrfq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RdRUserFollowersSlice.
func (rrfq *RdRUserFollowersQuery) All(ctx context.Context) ([]*RdRUserFollowers, error) {
	ctx = setContextOp(ctx, rrfq.ctx, "All")
	if err := rrfq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RdRUserFollowers, *RdRUserFollowersQuery]()
	return withInterceptors[[]*RdRUserFollowers](ctx, rrfq, qr, rrfq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rrfq *RdRUserFollowersQuery) AllX(ctx context.Context) []*RdRUserFollowers {
	nodes, err := rrfq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RdRUserFollowers IDs.
func (rrfq *RdRUserFollowersQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	ctx = setContextOp(ctx, rrfq.ctx, "IDs")
	if err := rrfq.Select(rdruserfollowers.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rrfq *RdRUserFollowersQuery) IDsX(ctx context.Context) []int64 {
	ids, err := rrfq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rrfq *RdRUserFollowersQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rrfq.ctx, "Count")
	if err := rrfq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rrfq, querierCount[*RdRUserFollowersQuery](), rrfq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rrfq *RdRUserFollowersQuery) CountX(ctx context.Context) int {
	count, err := rrfq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rrfq *RdRUserFollowersQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rrfq.ctx, "Exist")
	switch _, err := rrfq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rrfq *RdRUserFollowersQuery) ExistX(ctx context.Context) bool {
	exist, err := rrfq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RdRUserFollowersQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rrfq *RdRUserFollowersQuery) Clone() *RdRUserFollowersQuery {
	if rrfq == nil {
		return nil
	}
	return &RdRUserFollowersQuery{
		config:     rrfq.config,
		ctx:        rrfq.ctx.Clone(),
		order:      append([]OrderFunc{}, rrfq.order...),
		inters:     append([]Interceptor{}, rrfq.inters...),
		predicates: append([]predicate.RdRUserFollowers{}, rrfq.predicates...),
		// clone intermediate query.
		sql:  rrfq.sql.Clone(),
		path: rrfq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UID int32 `json:"uid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RdRUserFollowers.Query().
//		GroupBy(rdruserfollowers.FieldUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rrfq *RdRUserFollowersQuery) GroupBy(field string, fields ...string) *RdRUserFollowersGroupBy {
	rrfq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RdRUserFollowersGroupBy{build: rrfq}
	grbuild.flds = &rrfq.ctx.Fields
	grbuild.label = rdruserfollowers.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UID int32 `json:"uid,omitempty"`
//	}
//
//	client.RdRUserFollowers.Query().
//		Select(rdruserfollowers.FieldUID).
//		Scan(ctx, &v)
func (rrfq *RdRUserFollowersQuery) Select(fields ...string) *RdRUserFollowersSelect {
	rrfq.ctx.Fields = append(rrfq.ctx.Fields, fields...)
	sbuild := &RdRUserFollowersSelect{RdRUserFollowersQuery: rrfq}
	sbuild.label = rdruserfollowers.Label
	sbuild.flds, sbuild.scan = &rrfq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RdRUserFollowersSelect configured with the given aggregations.
func (rrfq *RdRUserFollowersQuery) Aggregate(fns ...AggregateFunc) *RdRUserFollowersSelect {
	return rrfq.Select().Aggregate(fns...)
}

func (rrfq *RdRUserFollowersQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rrfq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rrfq); err != nil {
				return err
			}
		}
	}
	for _, f := range rrfq.ctx.Fields {
		if !rdruserfollowers.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rrfq.path != nil {
		prev, err := rrfq.path(ctx)
		if err != nil {
			return err
		}
		rrfq.sql = prev
	}
	return nil
}

func (rrfq *RdRUserFollowersQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RdRUserFollowers, error) {
	var (
		nodes = []*RdRUserFollowers{}
		_spec = rrfq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RdRUserFollowers).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RdRUserFollowers{config: rrfq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rrfq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rrfq *RdRUserFollowersQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rrfq.querySpec()
	_spec.Node.Columns = rrfq.ctx.Fields
	if len(rrfq.ctx.Fields) > 0 {
		_spec.Unique = rrfq.ctx.Unique != nil && *rrfq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rrfq.driver, _spec)
}

func (rrfq *RdRUserFollowersQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   rdruserfollowers.Table,
			Columns: rdruserfollowers.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: rdruserfollowers.FieldID,
			},
		},
		From:   rrfq.sql,
		Unique: true,
	}
	if unique := rrfq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rrfq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rdruserfollowers.FieldID)
		for i := range fields {
			if fields[i] != rdruserfollowers.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rrfq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rrfq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rrfq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rrfq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rrfq *RdRUserFollowersQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rrfq.driver.Dialect())
	t1 := builder.Table(rdruserfollowers.Table)
	columns := rrfq.ctx.Fields
	if len(columns) == 0 {
		columns = rdruserfollowers.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rrfq.sql != nil {
		selector = rrfq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rrfq.ctx.Unique != nil && *rrfq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rrfq.predicates {
		p(selector)
	}
	for _, p := range rrfq.order {
		p(selector)
	}
	if offset := rrfq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rrfq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RdRUserFollowersGroupBy is the group-by builder for RdRUserFollowers entities.
type RdRUserFollowersGroupBy struct {
	selector
	build *RdRUserFollowersQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rrfgb *RdRUserFollowersGroupBy) Aggregate(fns ...AggregateFunc) *RdRUserFollowersGroupBy {
	rrfgb.fns = append(rrfgb.fns, fns...)
	return rrfgb
}

// Scan applies the selector query and scans the result into the given value.
func (rrfgb *RdRUserFollowersGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rrfgb.build.ctx, "GroupBy")
	if err := rrfgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RdRUserFollowersQuery, *RdRUserFollowersGroupBy](ctx, rrfgb.build, rrfgb, rrfgb.build.inters, v)
}

func (rrfgb *RdRUserFollowersGroupBy) sqlScan(ctx context.Context, root *RdRUserFollowersQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rrfgb.fns))
	for _, fn := range rrfgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rrfgb.flds)+len(rrfgb.fns))
		for _, f := range *rrfgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rrfgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rrfgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RdRUserFollowersSelect is the builder for selecting fields of RdRUserFollowers entities.
type RdRUserFollowersSelect struct {
	*RdRUserFollowersQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rrfs *RdRUserFollowersSelect) Aggregate(fns ...AggregateFunc) *RdRUserFollowersSelect {
	rrfs.fns = append(rrfs.fns, fns...)
	return rrfs
}

// Scan applies the selector query and scans the result into the given value.
func (rrfs *RdRUserFollowersSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rrfs.ctx, "Select")
	if err := rrfs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RdRUserFollowersQuery, *RdRUserFollowersSelect](ctx, rrfs.RdRUserFollowersQuery, rrfs, rrfs.inters, v)
}

func (rrfs *RdRUserFollowersSelect) sqlScan(ctx context.Context, root *RdRUserFollowersQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rrfs.fns))
	for _, fn := range rrfs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rrfs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rrfs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
