// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/rdmessage"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/rdmoment"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/rdrmomentsfollowing"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/rdruserfollowers"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/rdruserfollowing"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/rduser"
	"github.com/fxkt-tech/raiden/app/mainsite/service/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	rdmessageFields := schema.RdMessage{}.Fields()
	_ = rdmessageFields
	// rdmessageDescCreateTime is the schema descriptor for create_time field.
	rdmessageDescCreateTime := rdmessageFields[4].Descriptor()
	// rdmessage.DefaultCreateTime holds the default value on creation for the create_time field.
	rdmessage.DefaultCreateTime = rdmessageDescCreateTime.Default.(func() time.Time)
	rdmomentFields := schema.RdMoment{}.Fields()
	_ = rdmomentFields
	// rdmomentDescType is the schema descriptor for type field.
	rdmomentDescType := rdmomentFields[1].Descriptor()
	// rdmoment.DefaultType holds the default value on creation for the type field.
	rdmoment.DefaultType = rdmomentDescType.Default.(int32)
	// rdmomentDescPublishTime is the schema descriptor for publish_time field.
	rdmomentDescPublishTime := rdmomentFields[6].Descriptor()
	// rdmoment.DefaultPublishTime holds the default value on creation for the publish_time field.
	rdmoment.DefaultPublishTime = rdmomentDescPublishTime.Default.(func() time.Time)
	rdrmomentsfollowingFields := schema.RdRMomentsFollowing{}.Fields()
	_ = rdrmomentsfollowingFields
	// rdrmomentsfollowingDescMomentID is the schema descriptor for moment_id field.
	rdrmomentsfollowingDescMomentID := rdrmomentsfollowingFields[1].Descriptor()
	// rdrmomentsfollowing.DefaultMomentID holds the default value on creation for the moment_id field.
	rdrmomentsfollowing.DefaultMomentID = rdrmomentsfollowingDescMomentID.Default.(int64)
	// rdrmomentsfollowingDescMomentType is the schema descriptor for moment_type field.
	rdrmomentsfollowingDescMomentType := rdrmomentsfollowingFields[2].Descriptor()
	// rdrmomentsfollowing.DefaultMomentType holds the default value on creation for the moment_type field.
	rdrmomentsfollowing.DefaultMomentType = rdrmomentsfollowingDescMomentType.Default.(int32)
	// rdrmomentsfollowingDescPublishTime is the schema descriptor for publish_time field.
	rdrmomentsfollowingDescPublishTime := rdrmomentsfollowingFields[8].Descriptor()
	// rdrmomentsfollowing.DefaultPublishTime holds the default value on creation for the publish_time field.
	rdrmomentsfollowing.DefaultPublishTime = rdrmomentsfollowingDescPublishTime.Default.(func() time.Time)
	rdruserfollowersFields := schema.RdRUserFollowers{}.Fields()
	_ = rdruserfollowersFields
	// rdruserfollowersDescCreateTime is the schema descriptor for create_time field.
	rdruserfollowersDescCreateTime := rdruserfollowersFields[3].Descriptor()
	// rdruserfollowers.DefaultCreateTime holds the default value on creation for the create_time field.
	rdruserfollowers.DefaultCreateTime = rdruserfollowersDescCreateTime.Default.(func() time.Time)
	rdruserfollowingFields := schema.RdRUserFollowing{}.Fields()
	_ = rdruserfollowingFields
	// rdruserfollowingDescCreateTime is the schema descriptor for create_time field.
	rdruserfollowingDescCreateTime := rdruserfollowingFields[3].Descriptor()
	// rdruserfollowing.DefaultCreateTime holds the default value on creation for the create_time field.
	rdruserfollowing.DefaultCreateTime = rdruserfollowingDescCreateTime.Default.(func() time.Time)
	rduserFields := schema.RdUser{}.Fields()
	_ = rduserFields
	// rduserDescNick is the schema descriptor for nick field.
	rduserDescNick := rduserFields[1].Descriptor()
	// rduser.NickValidator is a validator for the "nick" field. It is called by the builders before save.
	rduser.NickValidator = rduserDescNick.Validators[0].(func(string) error)
	// rduserDescStatus is the schema descriptor for status field.
	rduserDescStatus := rduserFields[2].Descriptor()
	// rduser.DefaultStatus holds the default value on creation for the status field.
	rduser.DefaultStatus = rduserDescStatus.Default.(int32)
	// rduserDescCreateTime is the schema descriptor for create_time field.
	rduserDescCreateTime := rduserFields[3].Descriptor()
	// rduser.DefaultCreateTime holds the default value on creation for the create_time field.
	rduser.DefaultCreateTime = rduserDescCreateTime.Default.(func() time.Time)
}
